# Generated by Django 3.1.6 on 2021-02-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='newsid',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
