# Generated by Django 3.1.6 on 2021-02-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo2', '0003_auto_20210210_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotesmodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tributemodel',
            name='id',
        ),
        migrations.AddField(
            model_name='quotesmodel',
            name='quotesid',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tributemodel',
            name='tributeid',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
