# Generated by Django 3.1.6 on 2021-02-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo2', '0004_auto_20210210_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotesmodel',
            name='quotesid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tributemodel',
            name='tributeid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
